"""empty message

Revision ID: 28305959f15c
Revises: 5d35e4c8896c
Create Date: 2026-04-05 12:14:53.457353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28305959f15c'
down_revision = '5d35e4c8896c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('issue_type', sa.Enum('COMPLAINT', 'REQUEST', name='issuetype'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'PRIORITIZED', 'ON_HOLD', 'RESOLVED', 'CLOSED', 'REJECTED', name='issuestatus'), nullable=False),
    sa.Column('urgency_score', sa.Integer(), nullable=True),
    sa.Column('impact_score', sa.Integer(), nullable=True),
    sa.Column('aging_score', sa.Integer(), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('priority_level', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='prioritylevel'), nullable=True),
    sa.Column('priority_override', sa.Boolean(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('review_notes', sa.String(length=300), nullable=True),
    sa.Column('hold_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['issue_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('floors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('floors', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.drop_table('issues')
    op.drop_table('issue_categories')
    # ### end Alembic commands ###
