"""Set FK key nullable to False in floors and rooms table

Revision ID: 40ab2b9964ab
Revises: b396c4263216
Create Date: 2026-03-23 21:17:07.718540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ab2b9964ab'
down_revision = 'b396c4263216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('floors', schema=None) as batch_op:
        batch_op.alter_column('building_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('floor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('floor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('floors', schema=None) as batch_op:
        batch_op.alter_column('building_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
