"""Changed password_hash nullable to True, added is_password_set, opt_code and otp_expiry columns to users table

Revision ID: 51dbd44355bb
Revises: 40ab2b9964ab
Create Date: 2026-03-25 22:14:54.434648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51dbd44355bb'
down_revision = '40ab2b9964ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_password_set', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('otp_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('opt_expiry', sa.DateTime(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('opt_expiry')
        batch_op.drop_column('otp_code')
        batch_op.drop_column('is_password_set')

    # ### end Alembic commands ###
