"""Moved opt columns from user table to newly created otp table

Revision ID: 5d35e4c8896c
Revises: 51dbd44355bb
Create Date: 2026-04-01 13:31:40.567913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d35e4c8896c'
down_revision = '51dbd44355bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp_hash', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_otps', schema=None) as batch_op:
        batch_op.create_index('idx_user_purpose_active', ['user_id', 'purpose', 'is_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_otps_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('opt_expiry')
        batch_op.drop_column('otp_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_code', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('opt_expiry', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('user_otps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_otps_user_id'))
        batch_op.drop_index('idx_user_purpose_active')

    op.drop_table('user_otps')
    # ### end Alembic commands ###
