"""Changed floors to floor in rooms table and added unique constraints in floors and rooms tables

Revision ID: b396c4263216
Revises: b346c19ee02b
Create Date: 2026-03-23 21:13:07.302610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b396c4263216'
down_revision = 'b346c19ee02b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('floors', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_floor_building', ['number', 'building_id'])

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_room_floor', ['name', 'floor_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint('uq_room_floor', type_='unique')

    with op.batch_alter_table('floors', schema=None) as batch_op:
        batch_op.drop_constraint('uq_floor_building', type_='unique')

    # ### end Alembic commands ###
