"""removed UNDER_REVIEW and APPROVED from enums.py , migrating incase of updating db to PSQL on production

Revision ID: f463fc0de0f6
Revises: 4b24e20300e8
Create Date: 2026-04-07 21:07:32.730480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f463fc0de0f6'
down_revision = '4b24e20300e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('SUBMITTED', 'PRIORITIZED', 'ON_HOLD', 'RESOLVED', 'CLOSED', 'REJECTED', name='issuestatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('SUBMITTED', 'PRIORITIZED', 'ON_HOLD', 'RESOLVED', 'CLOSED', 'REJECTED', name='issuestatus'),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###
